name: KyleShawn
favicon: null
layout_spectrum: 0.26688812603242695
typography_spectrum: 0.6927403488662094
title: taking it ten seconds at a time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.39849373581819236
  lightness: 0.6780609942506999
  saturation: 0.20664417557418346
  rhythmicContrast: 0.021669939160346985
purpose: []
