name: KyleShawn
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55319
title: this is me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#080d11'
    - '#77d38d'
    - '#d5a598'
    - '#657083'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
