name: KyleShawn
favicon: null
layout_spectrum: 0.15838
typography_spectrum: 0.55319
title: this is me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#14141c'
    - '#8d9194'
    - '#b8bdc3'
    - '#6d6d6b'
    - '#127bc5'
  brandStrength: 0.3125
  lightness: 0.6780609942506999
  saturation: 0.125
  rhythmicContrast: 0.021669939160346985
purpose: []
